name: SmScavenger
version: '${project.version}'
main: me.smudge.smscavenger.SmScavenger
api-version: 1.16
authors: [ Smudge ]
soft-depend:
  - HeadDatabase
commands:
  scav:
    usage: /scav <command>
    description: Main Command, do /scav for help